/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import projetointegrador.objects.Autores;
import projetointegrador.telas.TelaInfoAutor;
import projetointegrador.telas.TelaPrincipal;

/**
 *
 * @author Gato Sagrado
 */
public class PnAutorBuscarAutores extends javax.swing.JPanel {

    public int id;

    /**
     * Creates new form PnAutorBuscarAutor
     */
    public PnAutorBuscarAutores(Autores autor) {
        initComponents();
        this.id = autor.getId();
        LbNome.setText(autor.getNome());
        LbMovimento.setText(autor.getMovimento().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtAutor = new javax.swing.JButton();
        LbMovimento = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 65));
        setMinimumSize(new java.awt.Dimension(1180, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtAutor.setBackground(new java.awt.Color(144, 144, 144));
        BtAutor.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtAutor.setForeground(new java.awt.Color(109, 37, 172));
        BtAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais.png"))); // NOI18N
        BtAutor.setToolTipText("Abre as informações do autor");
        BtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAutorActionPerformed(evt);
            }
        });
        add(BtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 18, 30, 30));

        LbMovimento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbMovimento.setText("Movimento");
        add(LbMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        LbNome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbNome.setText("Nome");
        add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAutorActionPerformed
        TelaPrincipal.sobreporPainel(new TelaInfoAutor(id));
    }//GEN-LAST:event_BtAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAutor;
    private javax.swing.JLabel LbMovimento;
    private javax.swing.JLabel LbNome;
    // End of variables declaration//GEN-END:variables
}
