/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import projetointegrador.objects.Categorias;

/**
 *
 * @author Gato Sagrado
 */
public class PnCategorias extends javax.swing.JPanel {

    public int id;

    /**
     * Creates new form PnCategorias
     */
    public PnCategorias(Categorias categoria) {
        this.id = categoria.getId();
        initComponents();
        LbCategoria.setText(categoria.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCategoria = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        LbCategoria.setBackground(new java.awt.Color(109, 37, 172));
        LbCategoria.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbCategoria.setText("Categoria");
        LbCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 37, 172), 5));
        LbCategoria.setMaximumSize(new java.awt.Dimension(300, 38));
        LbCategoria.setMinimumSize(new java.awt.Dimension(10, 38));
        LbCategoria.setOpaque(true);
        add(LbCategoria);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbCategoria;
    // End of variables declaration//GEN-END:variables
}
