/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import projetointegrador.objects.Exemplares;

/**
 *
 * @author Gato Sagrado
 */
public class PnExemplarInfoLivro extends javax.swing.JPanel {

    /**
     * Creates new form PnExemplarInfoLivro
     */
    public PnExemplarInfoLivro(Exemplares exemplar) {
        initComponents();
        LbExId.setText(String.valueOf(exemplar.getId()));
        LbExLocal.setText(exemplar.getLocalizacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbExId = new javax.swing.JLabel();
        LbExLocal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 65));
        setMinimumSize(new java.awt.Dimension(1180, 65));
        setPreferredSize(new java.awt.Dimension(1180, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbExId.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbExId.setText("ID");
        add(LbExId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        LbExLocal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbExLocal.setText("Local");
        add(LbExLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbExId;
    private javax.swing.JLabel LbExLocal;
    // End of variables declaration//GEN-END:variables
}
