/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import javax.swing.JOptionPane;
import projetointegrador.dao.Conector;
import projetointegrador.dao.ExemplaresDAO;
import projetointegrador.objects.Exemplares;
import projetointegrador.telas.TelaCadastroExemplar;
import projetointegrador.telas.TelaInfoLivro;
import projetointegrador.telas.TelaPrincipal;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class PnExemplarGerenciar extends javax.swing.JPanel {

    public int id;
    private GlobalListener listener;

    /**
     * Creates new form PnExemplarGerenciar
     */
    public PnExemplarGerenciar(Exemplares exemplar) {
        initComponents();
        this.id = exemplar.getId();
        LbId.setText(String.valueOf(id));
        LbTitulo.setText(exemplar.getLivro().getTitulo());
        LbEditora.setText(exemplar.getLivro().getEditora().getNome());
        LbLocal.setText(exemplar.getLocalizacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtLivro = new javax.swing.JButton();
        LbTitulo = new javax.swing.JLabel();
        LbLocal = new javax.swing.JLabel();
        LbEditora = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 50));
        setMinimumSize(new java.awt.Dimension(1180, 50));
        setPreferredSize(new java.awt.Dimension(1180, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtLivro.setBackground(new java.awt.Color(144, 144, 144));
        BtLivro.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtLivro.setForeground(new java.awt.Color(109, 37, 172));
        BtLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais.png"))); // NOI18N
        BtLivro.setToolTipText("Abre as informações do livro que possui o exemplar");
        BtLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLivroActionPerformed(evt);
            }
        });
        add(BtLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 30, 30));

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbTitulo.setText("Título");
        add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, -1, -1));

        LbLocal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbLocal.setText("Local");
        add(LbLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 15, -1, -1));

        LbEditora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbEditora.setText("Editora");
        add(LbEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 15, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbId.setText("ID");
        add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        BtEditar.setBackground(new java.awt.Color(144, 144, 144));
        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconEdit.png"))); // NOI18N
        BtEditar.setToolTipText("Altera as informações do exemplar");
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));

        BtExcluir.setBackground(new java.awt.Color(144, 144, 144));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLixo.png"))); // NOI18N
        BtExcluir.setToolTipText("Exclui o exemplar");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLivroActionPerformed
        try {
            ExemplaresDAO exemplaresDao = new ExemplaresDAO(Conector.conectar());
            TelaPrincipal.sobreporPainel(new TelaInfoLivro(exemplaresDao.getIdLivro(id)));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_BtLivroActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        TelaPrincipal.sobreporPainel(new TelaCadastroExemplar(listener, id));
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            String input = JOptionPane.showInputDialog(null, "Excluir exemplares não exclui outros registros.\nEscreva exatamente (SIM) para confirmar, qualquer outro texto irá cancelar.");
            if (input.equals("SIM")) {
                ExemplaresDAO exemplaresDao = new ExemplaresDAO(Conector.conectar());
                exemplaresDao.excluir(id);
                JOptionPane.showMessageDialog(null, "Exemplar excluído.");
                listener.sinalGlobal();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    public void setListener(GlobalListener listener) {
        this.listener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtLivro;
    private javax.swing.JLabel LbEditora;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbLocal;
    private javax.swing.JLabel LbTitulo;
    // End of variables declaration//GEN-END:variables
}
