package projetointegrador.panels;

import projetointegrador.objects.Livros;
import projetointegrador.telas.TelaInfoLivro;
import projetointegrador.telas.TelaPrincipal;

public class PnLivroBuscarLivros extends javax.swing.JPanel {

    public int id;

    public PnLivroBuscarLivros(Livros livro) {
        initComponents();
        this.id = livro.getId();
        LbTitulo.setText(livro.getTitulo());
        LbAutor.setText(livro.getAutor().getNome());
        LbEditora.setText(livro.getEditora().getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtLivro = new javax.swing.JButton();
        LbTitulo = new javax.swing.JLabel();
        LbAutor = new javax.swing.JLabel();
        LbEditora = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 60));
        setMinimumSize(new java.awt.Dimension(1180, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtLivro.setBackground(new java.awt.Color(144, 144, 144));
        BtLivro.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtLivro.setForeground(new java.awt.Color(109, 37, 172));
        BtLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais.png"))); // NOI18N
        BtLivro.setToolTipText("Abre as informações do livro");
        BtLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLivroActionPerformed(evt);
            }
        });
        add(BtLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 15, 30, 30));

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbTitulo.setText("Titulo");
        add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        LbAutor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbAutor.setText("Nome do autor");
        add(LbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        LbEditora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbEditora.setText("Nome da editora");
        add(LbEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLivroActionPerformed
        TelaPrincipal.sobreporPainel(new TelaInfoLivro(id));
    }//GEN-LAST:event_BtLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtLivro;
    private javax.swing.JLabel LbAutor;
    private javax.swing.JLabel LbEditora;
    private javax.swing.JLabel LbTitulo;
    // End of variables declaration//GEN-END:variables
}
