/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import javax.swing.JOptionPane;
import projetointegrador.dao.Conector;
import projetointegrador.dao.LoginsDAO;
import projetointegrador.objects.Logins;
import projetointegrador.telas.TelaPrincipal;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class PnLoginGerenciar extends javax.swing.JPanel {

    public int id;
    private GlobalListener listener;

    /**
     * Creates new form PnLoginGerenciar
     */
    public PnLoginGerenciar(Logins login) {
        initComponents();
        this.id = login.getId();
        LbId.setText(String.valueOf(id));
        LbLogin.setText(login.getLogin());
        LbAcesso.setText(login.getAcesso());
        if (id == 1) {
            BtExcluir.setEnabled(false);
            BtExcluir.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbLogin = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtExcluir = new javax.swing.JButton();
        LbAcesso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 50));
        setMinimumSize(new java.awt.Dimension(1180, 50));
        setPreferredSize(new java.awt.Dimension(1180, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbLogin.setText("Login");
        add(LbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbId.setText("ID");
        add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        BtExcluir.setBackground(new java.awt.Color(144, 144, 144));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLixo.png"))); // NOI18N
        BtExcluir.setToolTipText("Exclui o login");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 30, 30));

        LbAcesso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbAcesso.setText("Acesso");
        add(LbAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 15, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            if (LbLogin.getText().equals(TelaPrincipal.getLogin())) {
                JOptionPane.showMessageDialog(null, "Não é possível excluir o login atual.");
            } else {
                String input = JOptionPane.showInputDialog(null, "Excluir o login não irá afetar outros registros.\nEscreva exatamente (SIM) para confirmar, qualquer outro texto irá cancelar.");
                if (input.equals("SIM")) {
                    LoginsDAO loginDao = new LoginsDAO(Conector.conectar());
                    loginDao.excluir(id);
                    listener.sinalGlobal();
                } else {
                    JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    public void setListener(GlobalListener listener) {
        this.listener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExcluir;
    private javax.swing.JLabel LbAcesso;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbLogin;
    // End of variables declaration//GEN-END:variables
}
