/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.panels;

import javax.swing.JOptionPane;
import projetointegrador.dao.Conector;
import projetointegrador.dao.MovimentosDAO;
import projetointegrador.objects.Movimentos;
import projetointegrador.telas.TelaCadastroSimples;
import projetointegrador.telas.TelaPrincipal;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class PnMovimentoGerenciar extends javax.swing.JPanel {

    public int id;
    private GlobalListener listener;

    /**
     * Creates new form PnMovimentoGerenciar
     */
    public PnMovimentoGerenciar(Movimentos movimento) {
        initComponents();
        this.id = movimento.getId();
        LbId.setText(String.valueOf(id));
        LbNome.setText(movimento.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbNome = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 144, 144));
        setMaximumSize(new java.awt.Dimension(1180, 50));
        setMinimumSize(new java.awt.Dimension(1180, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbNome.setText("Movimento");
        add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 15, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LbId.setText("ID");
        add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        BtEditar.setBackground(new java.awt.Color(144, 144, 144));
        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconEdit.png"))); // NOI18N
        BtEditar.setToolTipText("Altera as informações do movimento");
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 30, 30));

        BtExcluir.setBackground(new java.awt.Color(144, 144, 144));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLixo.png"))); // NOI18N
        BtExcluir.setToolTipText("Exclui o movimento");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
        TelaPrincipal.sobreporPainel(new TelaCadastroSimples(listener, id, 'm'));
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            String input = JOptionPane.showInputDialog(null, "Excluir este movimento irá também excluir todos os autores (livros e exemplares inclusive) deste cadastrados.\nEscreva exatamente (SIM) para confirmar, qualquer outro texto irá cancelar.");
            if (input.equals("SIM")) {
                MovimentosDAO movimentosDao = new MovimentosDAO(Conector.conectar());
                movimentosDao.excluir(id);
                JOptionPane.showMessageDialog(null, "Movimento excluído.");
                listener.sinalGlobal();
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    public void setListener(GlobalListener listener) {
        this.listener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbNome;
    // End of variables declaration//GEN-END:variables
}
