/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import java.util.List;
import projetointegrador.dao.Conector;
import projetointegrador.dao.LoginsDAO;
import projetointegrador.objects.LoginFactory;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class CadastroLogin extends javax.swing.JPanel {

    private GlobalListener listener;

    /**
     * Creates new form CadastroLogin
     */
    public CadastroLogin(GlobalListener origem) {
        initComponents();
        listener = origem;
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtSalvar = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        LbLogin = new javax.swing.JLabel();
        TxLogin = new javax.swing.JTextField();
        LbSenha = new javax.swing.JLabel();
        TxSenha = new javax.swing.JTextField();
        LbAcesso = new javax.swing.JLabel();
        CbAcesso = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtSalvar.setBackground(new java.awt.Color(109, 37, 172));
        BtSalvar.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        BtSalvar.setText("SALVAR");
        BtSalvar.setToolTipText("Salva os campos");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 250, 85));

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        LbLogin.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbLogin.setLabelFor(TxLogin);
        LbLogin.setText("Login:");
        add(LbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        TxLogin.setBackground(new java.awt.Color(153, 114, 188));
        TxLogin.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxLogin.setToolTipText("Defina o login");
        TxLogin.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 225, 950, -1));

        LbSenha.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbSenha.setLabelFor(TxSenha);
        LbSenha.setText("Senha:");
        add(LbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        TxSenha.setBackground(new java.awt.Color(153, 114, 188));
        TxSenha.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxSenha.setToolTipText("Defina a senha");
        TxSenha.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 425, 950, -1));

        LbAcesso.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbAcesso.setLabelFor(CbAcesso);
        LbAcesso.setText("Acesso:");
        add(LbAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        CbAcesso.setBackground(new java.awt.Color(153, 114, 188));
        CbAcesso.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        CbAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Administrador" }));
        CbAcesso.setSelectedIndex(-1);
        CbAcesso.setToolTipText("Selecione o autor na lista");
        add(CbAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 625, 950, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        LoginFactory fabrica = new LoginFactory();
        String acesso = fabrica.passarParaBancoDeDados((String) CbAcesso.getSelectedItem());
        LoginsDAO loginsDao = new LoginsDAO(Conector.conectar());
        loginsDao.cadastrar(TxLogin.getText(), TxSenha.getText(), acesso);
        listener.sinalGlobal();
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbAcesso;
    private javax.swing.JLabel LbAcesso;
    private javax.swing.JLabel LbLogin;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JTextField TxLogin;
    private javax.swing.JTextField TxSenha;
    // End of variables declaration//GEN-END:variables

    private void atualizar() {
        CbAcesso.removeAllItems();
        LoginFactory fabrica = new LoginFactory();
        List<String> lista = fabrica.getTiposLogin();
        for (String s : lista) {
            CbAcesso.addItem(s);
        }
        CbAcesso.setSelectedIndex(-1);
    }

}
