/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import projetointegrador.dao.AutoresDAO;
import projetointegrador.dao.Conector;
import projetointegrador.dao.MovimentosDAO;
import projetointegrador.objects.Autores;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class CadastroAutor extends javax.swing.JPanel {

    private GlobalListener listener;
    private int id;
    private File imagem;

    /**
     * Creates new form CadastroAutor
     */
    public CadastroAutor(GlobalListener origem, int id) {
        initComponents();
        this.id = id;
        this.listener = origem;
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtFechar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        LbNome = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        LbMovimento = new javax.swing.JLabel();
        CbMovimento = new javax.swing.JComboBox<>();
        LbNascimento = new javax.swing.JLabel();
        LbFalecimento = new javax.swing.JLabel();
        PnFoto = new javax.swing.JPanel();
        LbFoto = new javax.swing.JLabel();
        BtFoto = new javax.swing.JButton();
        LbCaminho = new javax.swing.JLabel();
        TxNascimento = new javax.swing.JFormattedTextField();
        TxFalecimento = new javax.swing.JFormattedTextField();
        LbBiografia = new javax.swing.JLabel();
        PnBiografia = new javax.swing.JScrollPane();
        TxBiografia = new javax.swing.JTextArea();
        LbVivo = new javax.swing.JLabel();
        CbVivo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        BtSalvar.setBackground(new java.awt.Color(109, 37, 172));
        BtSalvar.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        BtSalvar.setText("SALVAR");
        BtSalvar.setToolTipText("Salva os campos");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 250, 85));

        LbNome.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbNome.setLabelFor(TxNome);
        LbNome.setText("Nome:");
        add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        TxNome.setBackground(new java.awt.Color(153, 114, 188));
        TxNome.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxNome.setToolTipText("Insira o nome do autor");
        TxNome.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 125, 850, -1));

        LbMovimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbMovimento.setLabelFor(CbMovimento);
        LbMovimento.setText("Movimento:");
        add(LbMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        CbMovimento.setBackground(new java.awt.Color(153, 114, 188));
        CbMovimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        CbMovimento.setToolTipText("Selecione o movimento na lista");
        add(CbMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 225, 850, -1));

        LbNascimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbNascimento.setLabelFor(TxNascimento);
        LbNascimento.setText("Nascimento:");
        add(LbNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        LbFalecimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbFalecimento.setLabelFor(TxFalecimento);
        LbFalecimento.setText("Falecimento:");
        add(LbFalecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        PnFoto.setBackground(new java.awt.Color(144, 144, 144));
        PnFoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbFoto.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbFoto.setText("Foto:");
        PnFoto.add(LbFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        BtFoto.setBackground(new java.awt.Color(144, 144, 144));
        BtFoto.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtFoto.setForeground(new java.awt.Color(109, 37, 172));
        BtFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais.png"))); // NOI18N
        BtFoto.setToolTipText("Seleciona o caminho da imagem");
        BtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFotoActionPerformed(evt);
            }
        });
        PnFoto.add(BtFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        LbCaminho.setFont(new java.awt.Font("Arial", 0, 50)); // NOI18N
        LbCaminho.setText("Selecione uma imagem");
        PnFoto.add(LbCaminho, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        add(PnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 825, 1200, 70));

        TxNascimento.setBackground(new java.awt.Color(153, 114, 188));
        try {
            TxNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxNascimento.setToolTipText("Insira a data de nascimento do autor");
        TxNascimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxNascimento.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 325, 850, -1));

        TxFalecimento.setBackground(new java.awt.Color(153, 114, 188));
        try {
            TxFalecimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxFalecimento.setToolTipText("Insira a data de falecimento do autor, selecione \"Sim\" abaixo caso vivo");
        TxFalecimento.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxFalecimento.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxFalecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 425, 850, -1));

        LbBiografia.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbBiografia.setLabelFor(TxBiografia);
        LbBiografia.setText("Biografia:");
        add(LbBiografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        PnBiografia.setBackground(new java.awt.Color(153, 114, 188));
        PnBiografia.setBorder(null);
        PnBiografia.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TxBiografia.setBackground(new java.awt.Color(153, 114, 188));
        TxBiografia.setColumns(20);
        TxBiografia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxBiografia.setLineWrap(true);
        TxBiografia.setRows(5);
        TxBiografia.setToolTipText("Insira a biografia resumida do autor");
        TxBiografia.setWrapStyleWord(true);
        TxBiografia.setMaximumSize(new java.awt.Dimension(955, 1000000000));
        TxBiografia.setMinimumSize(new java.awt.Dimension(940, 150));
        PnBiografia.setViewportView(TxBiografia);

        add(PnBiografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 625, 850, 175));

        LbVivo.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbVivo.setLabelFor(TxFalecimento);
        LbVivo.setText("Ainda vivo:");
        add(LbVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        CbVivo.setBackground(new java.awt.Color(153, 114, 188));
        CbVivo.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        CbVivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        CbVivo.setToolTipText("Defina se o campo falecimento será considerado.");
        CbVivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbVivoActionPerformed(evt);
            }
        });
        add(CbVivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 525, 850, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if (!TxNome.getText().isEmpty() && CbMovimento.getSelectedIndex() != -1 && verificarData() && !TxBiografia.getText().isEmpty()) {
            String item = (String) CbMovimento.getSelectedItem();
            String dataFalecimento = null;
            if (CbVivo.getSelectedIndex() == 0) {
                dataFalecimento = TxFalecimento.getText();
            }
            String[] itemdividido = item.split("/");
            int idMovimento = Integer.parseInt(itemdividido[0]);
            AutoresDAO autoresDao = new AutoresDAO(Conector.conectar());
            if (id == -1) {
                autoresDao.cadastrar(TxNome.getText(), idMovimento, TxNascimento.getText(), dataFalecimento, TxBiografia.getText(), imagem);
            } else {
                autoresDao.alterar(id, TxNome.getText(), idMovimento, TxNascimento.getText(), dataFalecimento, TxBiografia.getText(), imagem);
            }
            listener.sinalGlobal();
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos. Apenas falecimento e imagem são opcionais.\nO formato da data é: DD/MM/AAAA");
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFotoActionPerformed
        JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png");
        select.setFileFilter(filtro);
        select.setAcceptAllFileFilterUsed(false);
        int confirmador = select.showOpenDialog(null);
        if (confirmador == JFileChooser.APPROVE_OPTION) {
            imagem = select.getSelectedFile();
            LbCaminho.setText(imagem.getName());
        }
    }//GEN-LAST:event_BtFotoActionPerformed

    private void CbVivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbVivoActionPerformed
        if (CbVivo.getSelectedIndex() == 0) {
            TxFalecimento.setEnabled(true);
        } else {
            TxFalecimento.setEnabled(false);
        }
    }//GEN-LAST:event_CbVivoActionPerformed

    private void atualizar() {
        CbMovimento.removeAllItems();
        MovimentosDAO movimentosDao = new MovimentosDAO(Conector.conectar());
        List<String> listaMovimentos = movimentosDao.listarCadastroAutor(id);
        for (String s : listaMovimentos) {
            CbMovimento.addItem(s);
        }
        if (id != -1) {
            CbMovimento.setSelectedIndex(0);
            AutoresDAO autoresDao = new AutoresDAO(Conector.conectar());
            Autores autor = autoresDao.exibirAutor(id);
            TxNome.setText(autor.getNome());
            TxNascimento.setText(autor.getDataNascimento());
            if (autor.getDataFalecimento() != null) {
                TxFalecimento.setText(autor.getDataFalecimento());
            } else {
                CbVivo.setSelectedIndex(1);
            }
            TxBiografia.setText(autor.getBiografia());
            if (autor.getFoto() != null) {
                LbCaminho.setText("Sem alteração");
            }
        } else {
            CbMovimento.setSelectedIndex(-1);
        }
    }

    private boolean verificarData() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        formato.setLenient(false);
        if (TxNascimento.isEditValid() && (TxFalecimento.isEditValid() || CbVivo.getSelectedIndex() == 1)) {
            try {
                formato.parse(TxNascimento.getText());
                if (CbVivo.getSelectedIndex() == 0) {
                    formato.parse(TxFalecimento.getText());
                }
                return true;
            } catch (ParseException e) {
                return false;
            }
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtFoto;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbMovimento;
    private javax.swing.JComboBox<String> CbVivo;
    private javax.swing.JLabel LbBiografia;
    private javax.swing.JLabel LbCaminho;
    private javax.swing.JLabel LbFalecimento;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JLabel LbMovimento;
    private javax.swing.JLabel LbNascimento;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbVivo;
    private javax.swing.JScrollPane PnBiografia;
    private javax.swing.JPanel PnFoto;
    private javax.swing.JTextArea TxBiografia;
    private javax.swing.JFormattedTextField TxFalecimento;
    private javax.swing.JFormattedTextField TxNascimento;
    private javax.swing.JTextField TxNome;
    // End of variables declaration//GEN-END:variables
}
