/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import javax.swing.JOptionPane;
import projetointegrador.dao.CategoriasDAO;
import projetointegrador.dao.Conector;
import projetointegrador.dao.EditorasDAO;
import projetointegrador.dao.MovimentosDAO;
import projetointegrador.objects.Categorias;
import projetointegrador.objects.Editoras;
import projetointegrador.objects.Movimentos;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class CadastroSimples extends javax.swing.JPanel {

    private GlobalListener listener;
    private int id;
    private char tipo;

    /**
     * Creates new form CadastroSimples
     */
    public CadastroSimples(GlobalListener origem, int id, char tipo) {
        initComponents();
        this.id = id;
        this.tipo = tipo;
        this.listener = origem;
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtSalvar = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        LbNome = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtSalvar.setBackground(new java.awt.Color(109, 37, 172));
        BtSalvar.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        BtSalvar.setText("SALVAR");
        BtSalvar.setToolTipText("Salva os campos");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 250, 85));

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        LbNome.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbNome.setText("Nome:");
        add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        TxNome.setBackground(new java.awt.Color(153, 114, 188));
        TxNome.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxNome.setToolTipText("Insira o título do livro");
        TxNome.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 425, 1010, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if (!TxNome.getText().isEmpty()) {
            switch (tipo) {
                case 'c' -> {
                    CategoriasDAO categoriasDao = new CategoriasDAO(Conector.conectar());
                    if (id == -1) {
                        categoriasDao.cadastrar(TxNome.getText());
                    } else {
                        categoriasDao.alterar(id, TxNome.getText());
                    }
                }
                case 'm' -> {
                    MovimentosDAO movimentosDao = new MovimentosDAO(Conector.conectar());
                    if (id == -1) {
                        movimentosDao.cadastrar(TxNome.getText());
                    } else {
                        movimentosDao.alterar(id, TxNome.getText());
                    }
                }
                case 'e' -> {
                    EditorasDAO editorasDao = new EditorasDAO(Conector.conectar());
                    if (id == -1) {
                        editorasDao.cadastrar(TxNome.getText());
                    } else {
                        editorasDao.alterar(id, TxNome.getText());
                    }
                }
            }
            listener.sinalGlobal();
        } else {
            JOptionPane.showMessageDialog(this, "Preencha o campo.");
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void atualizar() {
        if (id != -1) {
            switch (tipo) {
                case 'c' -> {
                    CategoriasDAO categoriasDao = new CategoriasDAO(Conector.conectar());
                    Categorias c = categoriasDao.getCategoria(id);
                    TxNome.setText(c.getNome());
                }
                case 'm' -> {
                    MovimentosDAO movimentosDao = new MovimentosDAO(Conector.conectar());
                    Movimentos m = movimentosDao.getMovimento(id);
                    TxNome.setText(m.getNome());
                }
                case 'e' -> {
                    EditorasDAO editorasDao = new EditorasDAO(Conector.conectar());
                    Editoras e = editorasDao.getEditora(id);
                    TxNome.setText(e.getNome());
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel LbNome;
    private javax.swing.JTextField TxNome;
    // End of variables declaration//GEN-END:variables
}
