/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

/**
 *
 * @author Gato Sagrado
 */
public class Gerenciar extends javax.swing.JPanel {

    /**
     * Creates new form Gerenciar
     */
    public Gerenciar() {
        initComponents();
        validarPermissao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtLivros = new javax.swing.JButton();
        BtExemplares = new javax.swing.JButton();
        BtAutores = new javax.swing.JButton();
        BtCategorias = new javax.swing.JButton();
        BtMovimentos = new javax.swing.JButton();
        BtEditoras = new javax.swing.JButton();
        BtLogins = new javax.swing.JButton();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtLivros.setBackground(new java.awt.Color(153, 114, 188));
        BtLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLivros.png"))); // NOI18N
        BtLivros.setToolTipText("Abre o gerenciamento de livros");
        BtLivros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLivrosSelected.png"))); // NOI18N
        BtLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLivrosActionPerformed(evt);
            }
        });
        add(BtLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 100, 275, 200));

        BtExemplares.setBackground(new java.awt.Color(153, 114, 188));
        BtExemplares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconExemplares.png"))); // NOI18N
        BtExemplares.setToolTipText("Abre o gerenciamento de exemplares");
        BtExemplares.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconExemplaresSelected.png"))); // NOI18N
        BtExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExemplaresActionPerformed(evt);
            }
        });
        add(BtExemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 100, 275, 200));

        BtAutores.setBackground(new java.awt.Color(153, 114, 188));
        BtAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconAutores.png"))); // NOI18N
        BtAutores.setToolTipText("Abre o gerenciamento de autores");
        BtAutores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconAutoresSelected.png"))); // NOI18N
        BtAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAutoresActionPerformed(evt);
            }
        });
        add(BtAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 100, 275, 200));

        BtCategorias.setBackground(new java.awt.Color(153, 114, 188));
        BtCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCategorias.png"))); // NOI18N
        BtCategorias.setToolTipText("Abre o gerenciamento de categorias");
        BtCategorias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconCategoriasSelected.png"))); // NOI18N
        BtCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCategoriasActionPerformed(evt);
            }
        });
        add(BtCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 412, 275, 200));

        BtMovimentos.setBackground(new java.awt.Color(153, 114, 188));
        BtMovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMovimentos.png"))); // NOI18N
        BtMovimentos.setToolTipText("Abre o gerenciamento de movimentos");
        BtMovimentos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMovimentosSelected.png"))); // NOI18N
        BtMovimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMovimentosActionPerformed(evt);
            }
        });
        add(BtMovimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 412, 275, 200));

        BtEditoras.setBackground(new java.awt.Color(153, 114, 188));
        BtEditoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconEditoras.png"))); // NOI18N
        BtEditoras.setToolTipText("Abre o gerenciamento de editoras");
        BtEditoras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconEditorasSelected.png"))); // NOI18N
        BtEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditorasActionPerformed(evt);
            }
        });
        add(BtEditoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 412, 275, 200));

        BtLogins.setBackground(new java.awt.Color(153, 114, 188));
        BtLogins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLogins.png"))); // NOI18N
        BtLogins.setToolTipText("Abre o gerenciamento de logins");
        BtLogins.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconLoginsSelected.png"))); // NOI18N
        BtLogins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLoginsActionPerformed(evt);
            }
        });
        add(BtLogins, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 724, 275, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void BtLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLivrosActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarLivros());
    }//GEN-LAST:event_BtLivrosActionPerformed

    private void BtExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExemplaresActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarExemplares());
    }//GEN-LAST:event_BtExemplaresActionPerformed

    private void BtAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAutoresActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarAutores());
    }//GEN-LAST:event_BtAutoresActionPerformed

    private void BtCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCategoriasActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarCategorias());
    }//GEN-LAST:event_BtCategoriasActionPerformed

    private void BtMovimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMovimentosActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarMovimentos());
    }//GEN-LAST:event_BtMovimentosActionPerformed

    private void BtEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditorasActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarEditoras());
    }//GEN-LAST:event_BtEditorasActionPerformed

    private void BtLoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLoginsActionPerformed
        TelaPrincipal.trocarPainel(new GerenciarLogins());
    }//GEN-LAST:event_BtLoginsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAutores;
    private javax.swing.JButton BtCategorias;
    private javax.swing.JButton BtEditoras;
    private javax.swing.JButton BtExemplares;
    private javax.swing.JButton BtLivros;
    private javax.swing.JButton BtLogins;
    private javax.swing.JButton BtMovimentos;
    // End of variables declaration//GEN-END:variables

    private void validarPermissao() {
        if (!TelaPrincipal.getLogin().permissaoGerenciarLogins()) {
            BtLogins.setEnabled(false);
            BtLogins.setVisible(false);
        }
    }
}
