/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.telas;

import projetointegrador.objects.Logins;
import projetointegrador.dao.Conector;
import projetointegrador.dao.LoginsDAO;
import javax.swing.JFrame;

/**
 *
 * @author Bento
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnScrollTela = new javax.swing.JScrollPane();
        PnTela = new javax.swing.JPanel();
        LbLogo = new javax.swing.JLabel();
        LbLogin = new javax.swing.JLabel();
        TxLogin = new javax.swing.JTextField();
        LbSenha = new javax.swing.JLabel();
        BtEntrar = new javax.swing.JButton();
        LbOu = new javax.swing.JLabel();
        BtCliente = new javax.swing.JButton();
        TxSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Kumori");
        setBackground(new java.awt.Color(186, 186, 186));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(144, 103));
        setSize(new java.awt.Dimension(1000, 500));

        PnScrollTela.setBackground(new java.awt.Color(186, 186, 186));
        PnScrollTela.setMaximumSize(new java.awt.Dimension(1440, 1024));
        PnScrollTela.setPreferredSize(new java.awt.Dimension(1440, 1024));
        PnScrollTela.setViewportView(PnTela);

        PnTela.setBackground(new java.awt.Color(186, 186, 186));
        PnTela.setMaximumSize(new java.awt.Dimension(1440, 1024));
        PnTela.setMinimumSize(new java.awt.Dimension(1440, 1024));
        PnTela.setPreferredSize(new java.awt.Dimension(1440, 1024));
        PnTela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoKumori.png"))); // NOI18N
        PnTela.add(LbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 1240, 300));

        LbLogin.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        LbLogin.setLabelFor(TxLogin);
        LbLogin.setText("Login");
        PnTela.add(LbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 250, 84));

        TxLogin.setBackground(new java.awt.Color(153, 114, 188));
        TxLogin.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        TxLogin.setToolTipText("Informe o seu login");
        TxLogin.setMargin(new java.awt.Insets(2, 15, 2, 15));
        TxLogin.setNextFocusableComponent(TxSenha);
        PnTela.add(TxLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 950, 84));

        LbSenha.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        LbSenha.setLabelFor(TxSenha);
        LbSenha.setText("Senha");
        PnTela.add(LbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 250, 84));

        BtEntrar.setBackground(new java.awt.Color(109, 37, 172));
        BtEntrar.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        BtEntrar.setText("ENTRAR");
        BtEntrar.setToolTipText("Realiza login usando a senha informada");
        BtEntrar.setNextFocusableComponent(BtCliente);
        BtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEntrarActionPerformed(evt);
            }
        });
        PnTela.add(BtEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 675, 1240, 110));

        LbOu.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        LbOu.setText("OU");
        PnTela.add(LbOu, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 795, -1, -1));

        BtCliente.setBackground(new java.awt.Color(153, 114, 172));
        BtCliente.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        BtCliente.setText("Continuar como cliente");
        BtCliente.setToolTipText("Continuar sem login e funcionalidades limitadas");
        BtCliente.setNextFocusableComponent(TxLogin);
        BtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtClienteActionPerformed(evt);
            }
        });
        PnTela.add(BtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 855, 1240, 110));

        TxSenha.setBackground(new java.awt.Color(153, 114, 188));
        TxSenha.setFont(new java.awt.Font("Arial", 0, 74)); // NOI18N
        TxSenha.setToolTipText("Informe a senha");
        TxSenha.setMargin(new java.awt.Insets(2, 15, 2, 15));
        PnTela.add(TxSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 950, 84));

        PnScrollTela.setViewportView(PnTela);

        getContentPane().add(PnScrollTela, java.awt.BorderLayout.CENTER);
        PnScrollTela.setBounds(0, 0, getWidth(), getHeight());
        revalidate();
        repaint();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntrarActionPerformed
        LoginsDAO loginDao = new LoginsDAO(Conector.conectar());
        Logins login = loginDao.validarLogin(TxLogin.getText(), String.valueOf(TxSenha.getPassword()));
        if (login != null) {
            TelaPrincipal tela = new TelaPrincipal(login);
            tela.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtEntrarActionPerformed

    private void BtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtClienteActionPerformed
        Logins login = new Logins();
        TelaPrincipal tela = new TelaPrincipal(login);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCliente;
    private javax.swing.JButton BtEntrar;
    private javax.swing.JLabel LbLogin;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JLabel LbOu;
    private javax.swing.JLabel LbSenha;
    private javax.swing.JScrollPane PnScrollTela;
    private javax.swing.JPanel PnTela;
    private javax.swing.JTextField TxLogin;
    private javax.swing.JPasswordField TxSenha;
    // End of variables declaration//GEN-END:variables
}
