/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import java.util.List;
import javax.swing.JOptionPane;
import projetointegrador.dao.Conector;
import projetointegrador.dao.ExemplaresDAO;
import projetointegrador.dao.LivrosDAO;
import projetointegrador.objects.Exemplares;
import tools.GlobalListener;

/**
 *
 * @author Gato Sagrado
 */
public class TelaCadastroExemplar extends javax.swing.JPanel {

    private GlobalListener listener;
    private int id;

    /**
     * Creates new form CadastroExemplar
     */
    public TelaCadastroExemplar(GlobalListener origem, int id) {
        initComponents();
        this.id = id;
        this.listener = origem;
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtFechar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        LbLivro = new javax.swing.JLabel();
        CbLivro = new javax.swing.JComboBox<>();
        LbLocal = new javax.swing.JLabel();
        TxLocal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        BtSalvar.setBackground(new java.awt.Color(109, 37, 172));
        BtSalvar.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        BtSalvar.setText("SALVAR");
        BtSalvar.setToolTipText("Salva os campos");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 250, 85));

        LbLivro.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbLivro.setLabelFor(CbLivro);
        LbLivro.setText("Livro:");
        add(LbLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        CbLivro.setBackground(new java.awt.Color(153, 114, 188));
        CbLivro.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        CbLivro.setToolTipText("Selecione o livro na lista");
        add(CbLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, 1020, 76));

        LbLocal.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        LbLocal.setLabelFor(TxLocal);
        LbLocal.setText("Local:");
        add(LbLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        TxLocal.setBackground(new java.awt.Color(153, 114, 188));
        TxLocal.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        TxLocal.setToolTipText("Insira o local de armazenagem do exemplar");
        TxLocal.setMargin(new java.awt.Insets(2, 15, 2, 15));
        add(TxLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 525, 1020, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if (!TxLocal.getText().isEmpty() && CbLivro.getSelectedIndex() != -1) {
            try {
                String item = (String) CbLivro.getSelectedItem();
                String[] itemDividido = item.split("/");
                int idlivro = Integer.parseInt(itemDividido[0]);
                ExemplaresDAO exemplaresDao = new ExemplaresDAO(Conector.conectar());
                if (id == -1) {
                    exemplaresDao.cadastrar(idlivro, TxLocal.getText());
                    JOptionPane.showMessageDialog(null, "Exemplar cadastrado.");
                } else {
                    exemplaresDao.alterar(id, idlivro, TxLocal.getText());
                    JOptionPane.showMessageDialog(null, "Exemplar alterado.");
                }
                listener.sinalGlobal();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um livro e defina a localização física deste exemplar.");
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void atualizar() {
        try {
            CbLivro.removeAllItems();
            LivrosDAO livrosDao = new LivrosDAO(Conector.conectar());
            List<String> lista = livrosDao.listarGerenciarExemplares(id);
            for (String s : lista) {
                CbLivro.addItem(s);
            }
            if (id != -1) {
                CbLivro.setSelectedIndex(0);
                ExemplaresDAO exemplaresDao = new ExemplaresDAO(Conector.conectar());
                Exemplares exemplar = exemplaresDao.getExemplar(id);
                TxLocal.setText(exemplar.getLocalizacao());
            } else {
                CbLivro.setSelectedIndex(-1);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbLivro;
    private javax.swing.JLabel LbLivro;
    private javax.swing.JLabel LbLocal;
    private javax.swing.JTextField TxLocal;
    // End of variables declaration//GEN-END:variables
}
