/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicScrollBarUI;
import projetointegrador.dao.CategoriasDAO;
import projetointegrador.dao.Conector;
import projetointegrador.dao.LivrosDAO;
import projetointegrador.objects.Livros;
import projetointegrador.panels.PnLivroBuscarLivros;

/**
 *
 * @author Bento
 */
public class TelaBuscarLivros extends javax.swing.JPanel {

    /**
     * Creates new form BuscarLivros
     */
    public TelaBuscarLivros() {
        initComponents();
        listar();
        atualizarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnFiltro = new javax.swing.JPanel();
        BtFechar = new javax.swing.JButton();
        TxAnoIn = new javax.swing.JFormattedTextField();
        TxAnoFin = new javax.swing.JFormattedTextField();
        BtConfirm = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        LbFiltro = new javax.swing.JLabel();
        LbAno = new javax.swing.JLabel();
        LbAno2 = new javax.swing.JLabel();
        LbCat = new javax.swing.JLabel();
        CbCat = new javax.swing.JComboBox<>();
        PnGlass = new javax.swing.JPanel();
        PnBusca = new javax.swing.JPanel();
        BtBusca = new javax.swing.JButton();
        TxBusca = new javax.swing.JTextField();
        BtFiltro = new javax.swing.JButton();
        LbTutorial = new javax.swing.JLabel();
        LbTutorial2 = new javax.swing.JLabel();
        LbTutorial3 = new javax.swing.JLabel();
        PnScroll = new javax.swing.JScrollPane();
        PnAux = new javax.swing.JPanel();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnFiltro.setBackground(new java.awt.Color(144, 144, 144));
        PnFiltro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        BtFechar.setText("X");
        BtFechar.setToolTipText("Fecha as opções de filtro");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        PnFiltro.add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 60, 60));

        TxAnoIn.setBackground(new java.awt.Color(153, 114, 188));
        TxAnoIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxAnoIn.setToolTipText("Insira o ano inicial, apenas 4 digitos");
        TxAnoIn.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        PnFiltro.add(TxAnoIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 85, 100, -1));

        TxAnoFin.setBackground(new java.awt.Color(153, 114, 188));
        TxAnoFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxAnoFin.setToolTipText("Insira o ano final, apenas 4 digitos");
        TxAnoFin.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        PnFiltro.add(TxAnoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 85, 100, -1));

        BtConfirm.setBackground(new java.awt.Color(109, 37, 172));
        BtConfirm.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        BtConfirm.setText("Confirmar");
        BtConfirm.setToolTipText("Aplica os filtros selecionados");
        BtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmActionPerformed(evt);
            }
        });
        PnFiltro.add(BtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 250, -1));

        BtLimpar.setBackground(new java.awt.Color(153, 114, 188));
        BtLimpar.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        BtLimpar.setText("Limpar");
        BtLimpar.setToolTipText("Limpa os filtros selecionados");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });
        PnFiltro.add(BtLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, -1));

        LbFiltro.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        LbFiltro.setText("Filtro");
        PnFiltro.add(LbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        LbAno.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LbAno.setText("Ano: De");
        PnFiltro.add(LbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        LbAno2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LbAno2.setText("até");
        PnFiltro.add(LbAno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        LbCat.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LbCat.setText("Categoria:");
        PnFiltro.add(LbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        CbCat.setBackground(new java.awt.Color(153, 114, 188));
        CbCat.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        CbCat.setToolTipText("Selecione o autor na lista");
        PnFiltro.add(CbCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 145, 350, -1));

        add(PnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 570, 285));
        PnFiltro.setVisible(false);

        PnGlass.setOpaque(false);
        add(PnGlass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 1024));
        PnGlass.setVisible(false);
        PnGlass.addMouseListener(new MouseAdapter(){});

        PnBusca.setBackground(new java.awt.Color(186, 186, 186));
        PnBusca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtBusca.setBackground(new java.awt.Color(109, 37, 172));
        BtBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscar.png"))); // NOI18N
        BtBusca.setMnemonic('p');
        BtBusca.setToolTipText("Busca o título com o filtro aplicado");
        BtBusca.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarDisabled.png"))); // NOI18N
        BtBusca.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarDisabled.png"))); // NOI18N
        BtBusca.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarDisabled.png"))); // NOI18N
        BtBusca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarSelected.png"))); // NOI18N
        BtBusca.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarSelected.png"))); // NOI18N
        BtBusca.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarSelected.png"))); // NOI18N
        BtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscaActionPerformed(evt);
            }
        });
        PnBusca.add(BtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 90, 90));

        TxBusca.setBackground(new java.awt.Color(153, 114, 188));
        TxBusca.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        TxBusca.setForeground(java.awt.Color.darkGray);
        TxBusca.setText("Buscar por título");
        TxBusca.setToolTipText("Digite o título do livro");
        TxBusca.setMargin(new java.awt.Insets(2, 15, 2, 15));
        TxBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TxBuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxBuscaFocusLost(evt);
            }
        });
        PnBusca.add(TxBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 980, 90));

        BtFiltro.setBackground(new java.awt.Color(153, 114, 188));
        BtFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltro.png"))); // NOI18N
        BtFiltro.setMnemonic('o');
        BtFiltro.setToolTipText("Abre as opções de filtro");
        BtFiltro.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroDisabled.png"))); // NOI18N
        BtFiltro.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroDisabled.png"))); // NOI18N
        BtFiltro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroDisabled.png"))); // NOI18N
        BtFiltro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroSelected.png"))); // NOI18N
        BtFiltro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroSelected.png"))); // NOI18N
        BtFiltro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconFIltroSelected.png"))); // NOI18N
        BtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFiltroActionPerformed(evt);
            }
        });
        PnBusca.add(BtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 90, 90));

        LbTutorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbTutorial.setLabelFor(BtBusca);
        LbTutorial.setText("Alt + P");
        PnBusca.add(LbTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1138, 5, -1, -1));

        LbTutorial2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbTutorial2.setLabelFor(BtFiltro);
        LbTutorial2.setText("Alt + O");
        PnBusca.add(LbTutorial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 5, -1, -1));

        LbTutorial3.setDisplayedMnemonic('i');
        LbTutorial3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbTutorial3.setLabelFor(TxBusca);
        LbTutorial3.setText("Alt + I");
        PnBusca.add(LbTutorial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, -1, -1));

        add(PnBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PnScroll.setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 186, 186)));
        PnScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PnScroll.setAlignmentX(0.0F);
        PnScroll.setAlignmentY(0.0F);

        PnAux.setBackground(new java.awt.Color(186, 186, 186));
        PnAux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PnScroll.setViewportView(PnAux);

        add(PnScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1240, 904));
        PnScroll.getVerticalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getHorizontalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getViewport().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(109, 37, 172);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void TxBuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxBuscaFocusGained
        if (TxBusca.getForeground().equals(Color.darkGray)) {
            TxBusca.setText("");
            TxBusca.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_TxBuscaFocusGained

    private void TxBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxBuscaFocusLost
        if (TxBusca.getText().equals("")) {
            TxBusca.setText("Buscar por título");
            TxBusca.setForeground(Color.darkGray);
        }
    }//GEN-LAST:event_TxBuscaFocusLost

    private void BtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscaActionPerformed
        listar();
    }//GEN-LAST:event_BtBuscaActionPerformed

    private void BtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFiltroActionPerformed
        PnFiltro.setVisible(true);
        BtFiltro.setEnabled(false);
        PnGlass.setVisible(true);
    }//GEN-LAST:event_BtFiltroActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        PnFiltro.setVisible(false);
        BtFiltro.setEnabled(true);
        PnGlass.setVisible(false);
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        TxAnoIn.setValue(null);
        TxAnoFin.setValue(null);
        CbCat.setSelectedIndex(-1);
    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmActionPerformed
        listar();
        PnFiltro.setVisible(false);
        BtFiltro.setEnabled(true);
        PnGlass.setVisible(false);
    }//GEN-LAST:event_BtConfirmActionPerformed

    private void listar() {
        LivrosDAO livrosDao = new LivrosDAO(Conector.conectar());
        String busca = "";
        String anoInicial = TxAnoIn.getText();
        String anoFinal = TxAnoFin.getText();
        String categoria = "";
        if (CbCat.getSelectedIndex() != -1) {
            categoria = CbCat.getSelectedItem().toString();
        }
        if (!TxBusca.getForeground().equals(Color.darkGray)) {
            busca = TxBusca.getText();
        }

        List<Livros> lista = livrosDao.listarBuscarLivros(busca, anoInicial, anoFinal, categoria);

        if (lista != null) {
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado.");
            }

            PnAux.removeAll();
            PnAux.setLayout(new BoxLayout(PnAux, BoxLayout.Y_AXIS));

            PnAux.add(Box.createVerticalStrut(40));
            for (int i = 0; i < lista.size(); i++) {
                PnLivroBuscarLivros painel = new PnLivroBuscarLivros(lista.get(i));
                painel.setAlignmentX(Component.CENTER_ALIGNMENT);
                PnAux.add(painel);
                if (i < lista.size() - 1) {
                    PnAux.add(Box.createVerticalStrut(40));
                }
            }

            PnAux.revalidate();
            PnAux.repaint();
        }
    }

    private void atualizarCombo() {
        CbCat.removeAllItems();
        CategoriasDAO categoriasDao = new CategoriasDAO(Conector.conectar());
        List<String> lista = categoriasDao.listarBuscarLivros();
        for (String s : lista) {
            CbCat.addItem(s);
        }
        CbCat.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBusca;
    private javax.swing.JButton BtConfirm;
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtFiltro;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JComboBox<String> CbCat;
    private javax.swing.JLabel LbAno;
    private javax.swing.JLabel LbAno2;
    private javax.swing.JLabel LbCat;
    private javax.swing.JLabel LbFiltro;
    private javax.swing.JLabel LbTutorial;
    private javax.swing.JLabel LbTutorial2;
    private javax.swing.JLabel LbTutorial3;
    private javax.swing.JPanel PnAux;
    private javax.swing.JPanel PnBusca;
    private javax.swing.JPanel PnFiltro;
    private javax.swing.JPanel PnGlass;
    private javax.swing.JScrollPane PnScroll;
    private javax.swing.JFormattedTextField TxAnoFin;
    private javax.swing.JFormattedTextField TxAnoIn;
    private javax.swing.JTextField TxBusca;
    // End of variables declaration//GEN-END:variables
}
