/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.telas;

import projetointegrador.objects.Logins;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Bento
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    public TelaPrincipal(Logins login) {
        this.login = login;
        initComponents();
        validarPermissao();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        trocarPainel(new TelaBuscarLivros());
        trocarBotao(BtLivro);
    }
    private static Logins login;
    private static JPanel painelPrincipal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnScrollTela = new javax.swing.JScrollPane();
        PnMain = new javax.swing.JPanel();
        PnMenu = new javax.swing.JPanel();
        BtLivro = new javax.swing.JButton();
        BtAutor = new javax.swing.JButton();
        BtGerenciar = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();
        LbTutorial = new javax.swing.JLabel();
        LbTutorial2 = new javax.swing.JLabel();
        LbLogin = new javax.swing.JLabel();
        LbAcesso = new javax.swing.JLabel();
        PnPainel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Kumori");
        setBackground(new java.awt.Color(186, 186, 186));
        setMinimumSize(new java.awt.Dimension(144, 103));

        PnScrollTela.setBackground(new java.awt.Color(186, 186, 186));
        PnScrollTela.setViewportView(PnMain);

        PnMain.setBackground(new java.awt.Color(186, 186, 186));
        PnMain.setMaximumSize(new java.awt.Dimension(1440, 1024));
        PnMain.setMinimumSize(new java.awt.Dimension(1440, 1024));
        PnMain.setPreferredSize(new java.awt.Dimension(1440, 1024));
        PnMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnMenu.setBackground(new java.awt.Color(153, 114, 188));
        PnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtLivro.setBackground(new java.awt.Color(153, 114, 188));
        BtLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivros.png"))); // NOI18N
        BtLivro.setMnemonic('1');
        BtLivro.setToolTipText("Buscar Livros / Atalho: Alt + 1");
        BtLivro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtLivro.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosDisabled.png"))); // NOI18N
        BtLivro.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosDisabled.png"))); // NOI18N
        BtLivro.setFocusable(false);
        BtLivro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosDisabled.png"))); // NOI18N
        BtLivro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosSelected.png"))); // NOI18N
        BtLivro.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosSelected.png"))); // NOI18N
        BtLivro.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarLivrosSelected.png"))); // NOI18N
        BtLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLivroActionPerformed(evt);
            }
        });
        PnMenu.add(BtLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        BtAutor.setBackground(new java.awt.Color(153, 114, 188));
        BtAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutores.png"))); // NOI18N
        BtAutor.setMnemonic('2');
        BtAutor.setToolTipText("Buscar Autores / Atalho: Alt + 2");
        BtAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtAutor.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresDisabled.png"))); // NOI18N
        BtAutor.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresDisabled.png"))); // NOI18N
        BtAutor.setFocusable(false);
        BtAutor.setName(""); // NOI18N
        BtAutor.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresDisabled.png"))); // NOI18N
        BtAutor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresSelected.png"))); // NOI18N
        BtAutor.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresSelected.png"))); // NOI18N
        BtAutor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconBuscarAutoresSelected.png"))); // NOI18N
        BtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAutorActionPerformed(evt);
            }
        });
        PnMenu.add(BtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 150));

        BtGerenciar.setBackground(new java.awt.Color(153, 114, 188));
        BtGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciar.png"))); // NOI18N
        BtGerenciar.setMnemonic('3');
        BtGerenciar.setToolTipText("Gerenciar / Atalho: Alt + 3");
        BtGerenciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtGerenciar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarDisabled.png"))); // NOI18N
        BtGerenciar.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarDisabled.png"))); // NOI18N
        BtGerenciar.setFocusable(false);
        BtGerenciar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarDisabled.png"))); // NOI18N
        BtGerenciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarSelected.png"))); // NOI18N
        BtGerenciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarSelected.png"))); // NOI18N
        BtGerenciar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconGerenciarSelected.png"))); // NOI18N
        BtGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGerenciarActionPerformed(evt);
            }
        });
        PnMenu.add(BtGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 150));

        BtSair.setBackground(new java.awt.Color(153, 114, 188));
        BtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSair.png"))); // NOI18N
        BtSair.setMnemonic('0');
        BtSair.setToolTipText("Sair / Atalho: Alt + 0");
        BtSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtSair.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairDisabled.png"))); // NOI18N
        BtSair.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairDisabled.png"))); // NOI18N
        BtSair.setFocusable(false);
        BtSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairDisabled.png"))); // NOI18N
        BtSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairSelected.png"))); // NOI18N
        BtSair.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairSelected.png"))); // NOI18N
        BtSair.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconSairSelected.png"))); // NOI18N
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });
        PnMenu.add(BtSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 874, 200, 150));

        LbTutorial.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        PnMenu.add(LbTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, -1, 30));

        LbTutorial2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LbTutorial2.setText("Alt + 0");
        PnMenu.add(LbTutorial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 840, -1, 30));

        LbLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        PnMenu.add(LbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 30));

        LbAcesso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        PnMenu.add(LbAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, 30));

        PnMain.add(PnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 1024));

        PnPainel.setBackground(new java.awt.Color(186, 186, 186));
        PnPainel.setMaximumSize(new java.awt.Dimension(1240, 1024));
        PnPainel.setMinimumSize(new java.awt.Dimension(1240, 1024));

        javax.swing.GroupLayout PnPainelLayout = new javax.swing.GroupLayout(PnPainel);
        PnPainel.setLayout(PnPainelLayout);
        PnPainelLayout.setHorizontalGroup(
            PnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        PnPainelLayout.setVerticalGroup(
            PnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );

        PnMain.add(PnPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1240, 1024));

        PnScrollTela.setViewportView(PnMain);

        getContentPane().add(PnScrollTela, java.awt.BorderLayout.CENTER);
        PnScrollTela.setBounds(0, 0, getWidth(), getHeight());
        revalidate();
        repaint();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAutorActionPerformed
        trocarPainel(new TelaBuscarAutores());
        trocarBotao(BtAutor);
    }//GEN-LAST:event_BtAutorActionPerformed

    private void BtGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGerenciarActionPerformed
        trocarPainel(new TelaGerenciar());
        trocarBotao(BtGerenciar);
    }//GEN-LAST:event_BtGerenciarActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        TelaLogin proximaTela = new TelaLogin();
        proximaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLivroActionPerformed
        trocarPainel(new TelaBuscarLivros());
        trocarBotao(BtLivro);
    }//GEN-LAST:event_BtLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAutor;
    private javax.swing.JButton BtGerenciar;
    private javax.swing.JButton BtLivro;
    private javax.swing.JButton BtSair;
    private javax.swing.JLabel LbAcesso;
    private javax.swing.JLabel LbLogin;
    private javax.swing.JLabel LbTutorial;
    private javax.swing.JLabel LbTutorial2;
    private javax.swing.JPanel PnMain;
    private javax.swing.JPanel PnMenu;
    private static javax.swing.JPanel PnPainel;
    private javax.swing.JScrollPane PnScrollTela;
    // End of variables declaration//GEN-END:variables

    public static Logins getLogin() {
        return login;
    }

    private void validarPermissao() {
        LbAcesso.setText(login.getAcesso());
        if (login.getLogin() != null) {
            LbLogin.setText(login.getLogin());
        }
        if (login.permissaoGerenciar()) {
            LbTutorial.setText("Alt + 1, 2, 3");
        } else {
            LbTutorial.setText("Alt + 1, 2");
            BtGerenciar.setEnabled(false);
            BtGerenciar.setVisible(false);
        }
    }

    public static void trocarPainel(JPanel novo) {
        PnPainel.removeAll();
        painelPrincipal = novo;
        painelPrincipal.setBounds(0, 0, 1240, 1024);
        PnPainel.add(painelPrincipal);
        PnPainel.revalidate();
        PnPainel.repaint();
    }

    public static void sobreporPainel(JPanel novo) {
        PnPainel.removeAll();
        novo.setBounds(0, 0, 1240, 1024);
        PnPainel.add(novo);
        PnPainel.revalidate();
        PnPainel.repaint();
    }

    public static void voltarPainel() {
        PnPainel.removeAll();
        painelPrincipal.setBounds(0, 0, 1240, 1024);
        PnPainel.add(painelPrincipal);
        PnPainel.revalidate();
        PnPainel.repaint();
    }

    private void trocarBotao(JButton botao) {
        BtAutor.setEnabled(true);
        BtGerenciar.setEnabled(true);
        BtLivro.setEnabled(true);
        botao.setEnabled(false);
    }
}
