/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetointegrador.telas;

import java.awt.Component;
import java.awt.Image;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicScrollBarUI;
import projetointegrador.dao.AutoresDAO;
import projetointegrador.dao.Conector;
import projetointegrador.dao.LivrosDAO;
import projetointegrador.objects.Autores;
import projetointegrador.objects.Livros;
import projetointegrador.panels.PnLivroInfoAutor;

/**
 *
 * @author Bento
 */
public class TelaInfoAutor extends javax.swing.JPanel {

    /**
     * Creates new form InfoAutor
     */
    public TelaInfoAutor(int id) {
        initComponents();
        exibir(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnScroll = new javax.swing.JScrollPane();
        PnAux = new javax.swing.JPanel();
        PnInfo = new javax.swing.JPanel();
        LbFoto = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        LbMovimento = new javax.swing.JLabel();
        LbNasc = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtFechar = new javax.swing.JButton();
        PnBiografia = new javax.swing.JScrollPane();
        TxBiografia = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnScroll.setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 186, 186)));
        PnScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PnScroll.setAlignmentX(0.0F);
        PnScroll.setAlignmentY(0.0F);

        PnAux.setBackground(new java.awt.Color(186, 186, 186));
        PnAux.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24))); // NOI18N
        PnAux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PnScroll.setViewportView(PnAux);

        add(PnScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1240, 540));
        PnScroll.getVerticalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getHorizontalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getViewport().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(109, 37, 172);
            }
        });

        PnInfo.setBackground(new java.awt.Color(153, 114, 188));
        PnInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconNoImage.png"))); // NOI18N
        PnInfo.add(LbFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 225, 225));

        LbNome.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        LbNome.setText("Nome");
        PnInfo.add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 20, -1, -1));

        LbMovimento.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbMovimento.setText("Movimento");
        PnInfo.add(LbMovimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 75, -1, -1));

        LbNasc.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbNasc.setText("Nascimento - Falecimento");
        PnInfo.add(LbNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbId.setText("ID: id");
        PnInfo.add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 75, -1, -1));

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        PnInfo.add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        PnBiografia.setBackground(new java.awt.Color(153, 114, 188));
        PnBiografia.setBorder(null);
        PnBiografia.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TxBiografia.setEditable(false);
        TxBiografia.setBackground(new java.awt.Color(153, 114, 188));
        TxBiografia.setColumns(20);
        TxBiografia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxBiografia.setLineWrap(true);
        TxBiografia.setRows(5);
        TxBiografia.setText("Biografia");
        TxBiografia.setWrapStyleWord(true);
        TxBiografia.setMaximumSize(new java.awt.Dimension(955, 1000000000));
        TxBiografia.setMinimumSize(new java.awt.Dimension(940, 150));
        PnBiografia.setViewportView(TxBiografia);

        PnInfo.add(PnBiografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1200, 200));

        add(PnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void exibir(int id) {
        try {
            AutoresDAO autoresDao = new AutoresDAO(Conector.conectar());
            Autores autor = autoresDao.exibirAutor(id);
            if (autor.getFoto() != null) {
                Image imagemAjustada = autor.getFoto().getScaledInstance(225, 225, Image.SCALE_SMOOTH);
                ImageIcon icone = new ImageIcon(imagemAjustada);
                LbFoto.setIcon(icone);
            }
            LbNome.setText(autor.getNome());
            LbId.setText("ID: " + id);
            LbMovimento.setText(autor.getMovimento().getNome());
            LbNasc.setText(autor.getDataNascimento());
            if (autor.getDataFalecimento() != null) {
                LbNasc.setText(LbNasc.getText() + " - " + autor.getDataFalecimento());
            }
            TxBiografia.setText(autor.getBiografia());

            LivrosDAO livrosDao = new LivrosDAO(Conector.conectar());
            List<Livros> lista = livrosDao.exbirLivrosAutor(id);
            if (lista != null) {
                PnAux.removeAll();
                PnAux.setLayout(new BoxLayout(PnAux, BoxLayout.Y_AXIS));

                PnAux.add(Box.createVerticalStrut(30));
                for (int i = 0; i < lista.size(); i++) {
                    PnLivroInfoAutor painel = new PnLivroInfoAutor(lista.get(i));
                    painel.setAlignmentX(Component.CENTER_ALIGNMENT);
                    PnAux.add(painel);
                    if (i < lista.size() - 1) {
                        PnAux.add(Box.createVerticalStrut(40));
                    }
                }

                PnAux.revalidate();
                PnAux.repaint();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbMovimento;
    private javax.swing.JLabel LbNasc;
    private javax.swing.JLabel LbNome;
    private javax.swing.JPanel PnAux;
    private javax.swing.JScrollPane PnBiografia;
    private javax.swing.JPanel PnInfo;
    private javax.swing.JScrollPane PnScroll;
    private javax.swing.JTextArea TxBiografia;
    // End of variables declaration//GEN-END:variables
}
