package projetointegrador.telas;

import java.awt.Component;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.plaf.basic.BasicScrollBarUI;
import projetointegrador.dao.CategoriasDAO;
import projetointegrador.dao.Conector;
import projetointegrador.dao.ExemplaresDAO;
import projetointegrador.dao.LivrosDAO;
import projetointegrador.objects.Categorias;
import projetointegrador.objects.Exemplares;
import projetointegrador.objects.Livros;
import projetointegrador.panels.PnCategorias;
import projetointegrador.panels.PnExemplarInfoLivro;

/**
 *
 * @author Bento
 */
public class TelaInfoLivro extends javax.swing.JPanel {

    private Livros livro;

    /**
     * Creates new form InfoLivro
     */
    public TelaInfoLivro(int id) {
        initComponents();
        exibir(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnInfo = new javax.swing.JPanel();
        LbCapa = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        LbAutor = new javax.swing.JLabel();
        BtAutor = new javax.swing.JButton();
        LbAno = new javax.swing.JLabel();
        LbEditora = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        BtFechar = new javax.swing.JButton();
        PnCategorias = new javax.swing.JPanel();
        PnSinopse = new javax.swing.JScrollPane();
        TxSinopse = new javax.swing.JTextArea();
        PnScroll = new javax.swing.JScrollPane();
        PnAux = new javax.swing.JPanel();

        setBackground(new java.awt.Color(186, 186, 186));
        setMaximumSize(new java.awt.Dimension(1240, 1024));
        setMinimumSize(new java.awt.Dimension(1240, 1024));
        setPreferredSize(new java.awt.Dimension(1240, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnInfo.setBackground(new java.awt.Color(153, 114, 188));
        PnInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbCapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconNoImage.png"))); // NOI18N
        PnInfo.add(LbCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 225, 300));

        LbTitulo.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        LbTitulo.setText("Título");
        PnInfo.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 20, -1, -1));

        LbAutor.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbAutor.setText("Nome do autor");
        PnInfo.add(LbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, -1, -1));

        BtAutor.setBackground(new java.awt.Color(153, 114, 188));
        BtAutor.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        BtAutor.setForeground(new java.awt.Color(109, 37, 172));
        BtAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconMais2.png"))); // NOI18N
        BtAutor.setToolTipText("Abre as informações do autor");
        BtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAutorActionPerformed(evt);
            }
        });
        PnInfo.add(BtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 75, 30, 30));

        LbAno.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbAno.setText("Ano");
        PnInfo.add(LbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, -1, -1));

        LbEditora.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbEditora.setText("Nome da editora");
        PnInfo.add(LbEditora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        LbId.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        LbId.setText("ID: id");
        PnInfo.add(LbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 75, -1, -1));

        BtFechar.setBackground(new java.awt.Color(109, 37, 172));
        BtFechar.setFont(new java.awt.Font("Arial", 0, 75)); // NOI18N
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconXis2.png"))); // NOI18N
        BtFechar.setToolTipText("Volta para a tela anterior");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        PnInfo.add(BtFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 20, 85, 85));

        PnCategorias.setBackground(new java.awt.Color(153, 114, 188));
        PnCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24))); // NOI18N
        PnCategorias.setMaximumSize(new java.awt.Dimension(1200, 125));
        PnCategorias.setMinimumSize(new java.awt.Dimension(1200, 100));
        PnCategorias.setPreferredSize(new java.awt.Dimension(1200, 100));
        PnCategorias.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        PnInfo.add(PnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 375, 1200, 125));

        PnSinopse.setBackground(new java.awt.Color(153, 114, 188));
        PnSinopse.setBorder(null);
        PnSinopse.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TxSinopse.setEditable(false);
        TxSinopse.setBackground(new java.awt.Color(153, 114, 188));
        TxSinopse.setColumns(20);
        TxSinopse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TxSinopse.setLineWrap(true);
        TxSinopse.setRows(5);
        TxSinopse.setText("Resumo do livro");
        TxSinopse.setWrapStyleWord(true);
        TxSinopse.setMaximumSize(new java.awt.Dimension(955, 1000000000));
        TxSinopse.setMinimumSize(new java.awt.Dimension(940, 150));
        PnSinopse.setViewportView(TxSinopse);

        PnInfo.add(PnSinopse, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 955, 200));

        add(PnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 520));

        PnScroll.setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(186, 186, 186)));
        PnScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PnScroll.setAlignmentX(0.0F);
        PnScroll.setAlignmentY(0.0F);

        PnAux.setBackground(new java.awt.Color(186, 186, 186));
        PnAux.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exemplares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24))); // NOI18N
        PnAux.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PnScroll.setViewportView(PnAux);

        add(PnScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1240, 500));
        PnScroll.getVerticalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getHorizontalScrollBar().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getViewport().setBackground(new java.awt.Color(186, 186, 186));
        PnScroll.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new java.awt.Color(109, 37, 172);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        TelaPrincipal.voltarPainel();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void BtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAutorActionPerformed
        TelaPrincipal.sobreporPainel(new TelaInfoAutor(livro.getAutor().getId()));
    }//GEN-LAST:event_BtAutorActionPerformed

    private void exibir(int id) {
        LivrosDAO livrosDao = new LivrosDAO(Conector.conectar());
        Livros livro = livrosDao.exibirLivro(id);
        this.livro = livro;
        if (livro.getCapa() != null) {
            LbCapa.setIcon(livro.getCapa());
        }
        TxSinopse.setText(livro.getDescricao());
        LbId.setText("ID: " + String.valueOf(livro.getId()));
        LbEditora.setText(livro.getEditora().getNome());
        LbAutor.setText(livro.getAutor().getNome());
        LbAno.setText(String.valueOf(livro.getAno()));
        LbTitulo.setText(livro.getTitulo());

        CategoriasDAO categoriasDao = new CategoriasDAO(Conector.conectar());
        List<Categorias> listaCategorias = categoriasDao.getCategoriasLivro(id);
        for (Categorias cat : listaCategorias) {
            PnCategorias categoria = new PnCategorias(cat);
            PnCategorias.add(categoria);
        }

        ExemplaresDAO exemplaresDao = new ExemplaresDAO(Conector.conectar());
        List<Exemplares> listaExemplares = exemplaresDao.listarExemplaresLivro(id);

        if (listaExemplares != null) {
            PnAux.removeAll();
            PnAux.setLayout(new BoxLayout(PnAux, BoxLayout.Y_AXIS));

            PnAux.add(Box.createVerticalStrut(30));
            for (int i = 0; i < listaExemplares.size(); i++) {
                PnExemplarInfoLivro painel = new PnExemplarInfoLivro(listaExemplares.get(i));
                painel.setAlignmentX(Component.CENTER_ALIGNMENT);
                PnAux.add(painel);
                if (i < listaExemplares.size() - 1) {
                    PnAux.add(Box.createVerticalStrut(40));
                }
            }

            PnAux.revalidate();
            PnAux.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAutor;
    private javax.swing.JButton BtFechar;
    private javax.swing.JLabel LbAno;
    private javax.swing.JLabel LbAutor;
    private javax.swing.JLabel LbCapa;
    private javax.swing.JLabel LbEditora;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel PnAux;
    private javax.swing.JPanel PnCategorias;
    private javax.swing.JPanel PnInfo;
    private javax.swing.JScrollPane PnScroll;
    private javax.swing.JScrollPane PnSinopse;
    private javax.swing.JTextArea TxSinopse;
    // End of variables declaration//GEN-END:variables
}
